#!/usr/bin/env bash
#
# SIDNVIM installer
#
# One command to set up Sidney's nvim + tmux config on a fresh Linux/WSL box:
#   1. install system dependencies (distro-aware)
#   2. prompt for your routes and write lua/config/local.lua (git-ignored)
#   3. symlink ~/.config/nvim  -> <repo>/nvim
#              ~/.tmux.conf    -> <repo>/tmux/tmux.conf
#   4. clone TPM into ~/.tmux/plugins/tpm
#
# Existing configs are backed up (not deleted) before symlinking.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colors ─────────────────────────────────────────────────────────
C_RESET='\033[0m'; C_BOLD='\033[1m'; C_GREEN='\033[32m'; C_YELLOW='\033[33m'
say()  { printf "${C_BOLD}%s${C_RESET}\n" "$*"; }
ok()   { printf "${C_GREEN}✓ %s${C_RESET}\n" "$*"; }
warn() { printf "${C_YELLOW}! %s${C_RESET}\n" "$*"; }

# ── Platform detection ────────────────────────────────────────────
is_wsl() { grep -qi microsoft /proc/version 2>/dev/null; }

detect_pm() {
  if command -v apt-get >/dev/null 2>&1; then echo apt
  elif command -v dnf >/dev/null 2>&1; then echo dnf
  elif command -v pacman >/dev/null 2>&1; then echo pacman
  else echo unknown; fi
}

# ── Dependency install ────────────────────────────────────────────
install_deps() {
  local pm="$1"
  say "Installing dependencies (package manager: $pm)..."

  case "$pm" in
    apt)
      sudo apt-get update
      sudo apt-get install -y make gcc unzip curl git ripgrep fd-find tree-sitter-cli tmux
      if is_wsl; then sudo apt-get install -y xclip; else sudo apt-get install -y xclip wl-clipboard; fi
      # Neovim stable via official release tarball (distro-agnostic, always current)
      if ! command -v nvim >/dev/null 2>&1; then
        local arch asset
        arch="$(uname -m)"
        case "$arch" in
          x86_64)  asset="nvim-linux-x86_64.tar.gz" ;;
          aarch64) asset="nvim-linux-arm64.tar.gz" ;;
          *) warn "unsupported arch $arch; install neovim manually"; asset="" ;;
        esac
        if [ -n "$asset" ]; then
          curl -fLo /tmp/nvim.tar.gz "https://github.com/neovim/neovim/releases/latest/download/$asset"
          sudo tar -C /usr/local --strip-components=1 -xzf /tmp/nvim.tar.gz
          rm -f /tmp/nvim.tar.gz
          ok "installed neovim (latest release)"
        fi
      fi
      # Ubuntu ships fd as `fdfind`; telescope expects `fd`
      if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
        sudo ln -sf "$(command -v fdfind)" /usr/local/bin/fd
        ok "symlinked fdfind -> fd"
      fi
      ;;
    dnf)
      sudo dnf install -y make gcc unzip curl git ripgrep fd-find tree-sitter-cli tmux neovim
      is_wsl || sudo dnf install -y xclip wl-clipboard
      ;;
    pacman)
      sudo pacman -S --needed --noconfirm make gcc unzip curl git ripgrep fd tree-sitter-cli tmux neovim
      is_wsl || sudo pacman -S --needed --noconfirm xclip wl-clipboard
      ;;
    *)
      warn "No supported package manager detected (apt/dnf/pacman)."
      warn "Install these manually: make gcc unzip curl git ripgrep fd tree-sitter-cli tmux neovim"
      ;;
  esac
}

# ── Route prompts → local.lua ─────────────────────────────────────
write_local_lua() {
  say "Configure your routes (used by the dashboard + Obsidian)."
  echo "Press Enter to accept the default shown in brackets."

  local projects notes
  read -r -p "Projects directory [~/code]: " projects || true
  projects="${projects:-~/code}"
  read -r -p "Notes / Obsidian vault directory [~/Documents/Notes/Obsidian]: " notes || true
  notes="${notes:-~/Documents/Notes/Obsidian}"

  # Long-bracket strings ([[ ... ]]) are literal in Lua — quotes and
  # backslashes in user input need no escaping.
  local out="$REPO_DIR/nvim/lua/config/local.lua"
  cat > "$out" <<EOF
-- Generated by install.sh — NOT tracked by git.
-- Edit freely; values here override the defaults in local.lua.example.
return {
  projects = [[$projects]],
  notes = [[$notes]],
  open_cmd = 'auto',
}
EOF
  ok "wrote $out"
}

# ── Symlink helper (backup, don't destroy) ────────────────────────
link() {
  local src="$1" dst="$2"
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    local bak="${dst}.bak.$(date +%Y%m%d%H%M%S)"
    mv "$dst" "$bak"
    warn "backed up existing $dst -> $bak"
  fi
  mkdir -p "$(dirname "$dst")"
  ln -s "$src" "$dst"
  ok "linked $dst -> $src"
}

# ── Main ──────────────────────────────────────────────────────────
say "SIDNVIM installer"
echo "repo: $REPO_DIR"

install_deps "$(detect_pm)"
write_local_lua

say "Symlinking configs..."
link "$REPO_DIR/nvim" "$HOME/.config/nvim"
link "$REPO_DIR/tmux/tmux.conf" "$HOME/.tmux.conf"

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  say "Cloning TPM..."
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
  ok "cloned TPM"
else
  ok "TPM already present"
fi

echo
say "Done."
echo "Next steps:"
echo "  1. Install a Nerd Font (see docs/install.md) and set your terminal to use it."
echo "  2. Launch nvim — lazy.nvim will install plugins on first run."
echo "  3. In tmux, press <prefix> + I to install tmux plugins (sensible, resurrect)."
echo "     (<prefix> is Ctrl+b by default.)"
