# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

####################### Sidney's Personal Tmux Configurations ###############################

#==============================
## Status bar appereance 
#==============================

# Status bar colors
set -g status-style 'bg=#202d3a fg=#8b949e'
set -g status-left-length 90
set -g status-right-length 50
 
# Status bar content
set -g status-left '#[fg=#00e68a,bold] #{host} [#S]: #[fg=#d4b31c,bold]#W #[fg=#5b636d]│ '
set -g status-right '#[fg=#5b636d]│ #[fg=#eceaed]%A %b/%d/%y #[fg=#5b636d]│ #[fg=#eceaed]%I:%M %p' ## should look like ( | 1:30 PM | Friday 31/Jul/26)


#==========================================
 ## Pane Customizations
#===========================================


## base index of panes and windows set to 1
set -g base-index 1
set -g pane-base-index 1

## renumber tmux panes automatically
set-option -g renumber-windows on

#==============================
## Mouse
#==============================

# Enable mouse support: scroll wheel scrolls pane history, click to select/resize panes
set -g mouse on

#==============================
## Key Bindings
#==============================

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
# Vim-style pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5 




# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
